// <auto-generated />
using System;
using DataAcces.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAcces.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260224183507_inclucionDeIndicesPorPerformance")]
    partial class inclucionDeIndicesPorPerformance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.AccessEvents", b =>
                {
                    b.Property<string>("DeviceSn")
                        .HasColumnType("text");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("AttendanceStatus")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Major")
                        .HasColumnType("integer");

                    b.Property<int>("Minor")
                        .HasColumnType("integer");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeDevice")
                        .HasColumnType("text");

                    b.HasKey("DeviceSn", "SerialNumber");

                    b.HasIndex("AttendanceStatus");

                    b.HasIndex("EmployeeNumber");

                    b.HasIndex("EventTimeUtc");

                    b.HasIndex("Minor");

                    b.HasIndex("DeviceSn", "EventTimeUtc");

                    b.HasIndex("Major", "Minor", "EventTimeUtc");

                    b.ToTable("AccessEvents", (string)null);
                });

            modelBuilder.Entity("Dominio.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidentialId")
                        .HasColumnType("integer");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("ResidentialId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Dominio.Jornada", b =>
                {
                    b.Property<string>("JornadaId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset?>("BreakInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BreakOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClockSn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusBreak")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusCheck")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JornadaId");

                    b.HasIndex("ClockSn");

                    b.HasIndex("StartAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("EmployeeNumber", "ClockSn", "StatusCheck");

                    b.ToTable("Jornadas", (string)null);
                });

            modelBuilder.Entity("Dominio.Reloj", b =>
                {
                    b.Property<int>("IdReloj")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceSn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPollEvent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPushEvent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<int>("ResidentialId")
                        .HasColumnType("integer");

                    b.HasKey("IdReloj");

                    b.HasIndex("DeviceSn")
                        .IsUnique();

                    b.HasIndex("ResidentialId");

                    b.ToTable("Relojes", (string)null);
                });

            modelBuilder.Entity("Dominio.Residential", b =>
                {
                    b.Property<int>("IdResidential")
                        .HasColumnType("integer");

                    b.Property<string>("IpActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdResidential");

                    b.ToTable("Residentials", (string)null);
                });

            modelBuilder.Entity("Dominio.Device", b =>
                {
                    b.HasOne("Dominio.Residential", "Residential")
                        .WithMany("Devices")
                        .HasForeignKey("ResidentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Residential");
                });

            modelBuilder.Entity("Dominio.Reloj", b =>
                {
                    b.HasOne("Dominio.Residential", "Residential")
                        .WithMany("Relojes")
                        .HasForeignKey("ResidentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Residential");
                });

            modelBuilder.Entity("Dominio.Residential", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Relojes");
                });
#pragma warning restore 612, 618
        }
    }
}
