// <auto-generated />
using System;
using DataAcces.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAcces.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260714210010_JornadaProjectionQueue")]
    partial class JornadaProjectionQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.AccessEvents", b =>
                {
                    b.Property<string>("DeviceSn")
                        .HasColumnType("text");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("AttendanceStatus")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Major")
                        .HasColumnType("integer");

                    b.Property<int>("Minor")
                        .HasColumnType("integer");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResidentialId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TimeDevice")
                        .HasColumnType("text");

                    b.HasKey("DeviceSn", "SerialNumber");

                    b.HasIndex("AttendanceStatus");

                    b.HasIndex("EmployeeNumber");

                    b.HasIndex("EventTimeUtc");

                    b.HasIndex("Minor");

                    b.HasIndex("DeviceSn", "EventTimeUtc");

                    b.HasIndex("EmployeeNumber", "ResidentialId", "EventTimeUtc");

                    b.HasIndex("Major", "Minor", "EventTimeUtc");

                    b.ToTable("AccessEvents", (string)null);
                });

            modelBuilder.Entity("Dominio.BackfillPollRunLog", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ClocksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ignored")
                        .HasColumnType("integer");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalClocks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWindows")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("RunId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("BackfillPollRuns", (string)null);
                });

            modelBuilder.Entity("Dominio.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResidentialId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("ResidentialId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Dominio.Jornada", b =>
                {
                    b.Property<string>("JornadaId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset?>("BreakInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BreakInDeviceSn")
                        .HasColumnType("text");

                    b.Property<long?>("BreakInSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("BreakOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BreakOutDeviceSn")
                        .HasColumnType("text");

                    b.Property<long?>("BreakOutSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("ClockSn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndDeviceSn")
                        .HasColumnType("text");

                    b.Property<long?>("EndSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IdentityDeviceSn")
                        .HasColumnType("text");

                    b.Property<long?>("IdentitySerialNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResidentialId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartDeviceSn")
                        .HasColumnType("text");

                    b.Property<long?>("StartSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusBreak")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusCheck")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("JornadaId");

                    b.HasIndex("ClockSn");

                    b.HasIndex("StartAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("EmployeeNumber", "ResidentialId", "StatusCheck");

                    b.HasIndex("EmployeeNumber", "ResidentialId", "IdentityDeviceSn", "IdentitySerialNumber")
                        .IsUnique();

                    b.ToTable("Jornadas", (string)null);
                });

            modelBuilder.Entity("Dominio.JornadaProjectionState", b =>
                {
                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<string>("ResidentialId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("AppliedRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DirtyFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequestedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EmployeeNumber", "ResidentialId");

                    b.HasIndex("DirtyFromUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc", "UpdatedAtUtc");

                    b.ToTable("JornadaProjectionStates", (string)null);
                });

            modelBuilder.Entity("Dominio.Reloj", b =>
                {
                    b.Property<string>("IdReloj")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceSn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPollEvent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPushEvent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<string>("ResidentialId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("IdReloj");

                    b.HasIndex("DeviceSn")
                        .IsUnique();

                    b.HasIndex("ResidentialId");

                    b.ToTable("Relojes", (string)null);
                });

            modelBuilder.Entity("Dominio.Residential", b =>
                {
                    b.Property<string>("IdResidential")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdResidential");

                    b.ToTable("Residentials", (string)null);
                });

            modelBuilder.Entity("Dominio.Device", b =>
                {
                    b.HasOne("Dominio.Residential", "Residential")
                        .WithMany("Devices")
                        .HasForeignKey("ResidentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Residential");
                });

            modelBuilder.Entity("Dominio.Reloj", b =>
                {
                    b.HasOne("Dominio.Residential", "Residential")
                        .WithMany("Relojes")
                        .HasForeignKey("ResidentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Residential");
                });

            modelBuilder.Entity("Dominio.Residential", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Relojes");
                });
#pragma warning restore 612, 618
        }
    }
}
