// <auto-generated />
using System;
using DataAcces.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAcces.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidentialId")
                        .HasColumnType("integer");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("ResidentialId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Dominio.Reloj", b =>
                {
                    b.Property<int>("IdReloj")
                        .HasColumnType("integer");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<int>("ResidentialId")
                        .HasColumnType("integer");

                    b.HasKey("IdReloj");

                    b.HasIndex("ResidentialId");

                    b.ToTable("Relojes", (string)null);
                });

            modelBuilder.Entity("Dominio.Residential", b =>
                {
                    b.Property<int>("IdResidential")
                        .HasColumnType("integer");

                    b.Property<string>("IpActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdResidential");

                    b.ToTable("Residentials", (string)null);
                });

            modelBuilder.Entity("Dominio.Device", b =>
                {
                    b.HasOne("Dominio.Residential", "Residential")
                        .WithMany("Devices")
                        .HasForeignKey("ResidentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Residential");
                });

            modelBuilder.Entity("Dominio.Reloj", b =>
                {
                    b.HasOne("Dominio.Residential", "Residential")
                        .WithMany("Relojes")
                        .HasForeignKey("ResidentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Residential");
                });

            modelBuilder.Entity("Dominio.Residential", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Relojes");
                });
#pragma warning restore 612, 618
        }
    }
}
